# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protoPackets.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protoPackets.proto',
  package='de.fu_berlin.maniac.packet_builder',
  serialized_pb='\n\x12protoPackets.proto\x12\"de.fu_berlin.maniac.packet_builder\"\x9c\x04\n\rPacketMessage\x12J\n\x04type\x18\x01 \x02(\x0e\x32<.de.fu_berlin.maniac.packet_builder.PacketMessage.packetType\x12\x15\n\rtransactionID\x18\x02 \x02(\x05\x12H\n\radvertMessage\x18\x04 \x01(\x0b\x32\x31.de.fu_berlin.maniac.packet_builder.AdvertMessage\x12\x42\n\nbidMessage\x18\x05 \x01(\x0b\x32..de.fu_berlin.maniac.packet_builder.BidMessage\x12H\n\rbidWinMessage\x18\x06 \x01(\x0b\x32\x31.de.fu_berlin.maniac.packet_builder.BidWinMessage\x12\x46\n\x0c\x63heckMessage\x18\x07 \x01(\x0b\x32\x30.de.fu_berlin.maniac.packet_builder.CheckMessage\x12\x44\n\x0b\x64\x61taMessage\x18\x08 \x01(\x0b\x32/.de.fu_berlin.maniac.packet_builder.DataMessage\"B\n\npacketType\x12\n\n\x06\x41\x44VERT\x10\x00\x12\x07\n\x03\x42ID\x10\x01\x12\n\n\x06\x42IDWIN\x10\x02\x12\t\n\x05\x43HECK\x10\x03\x12\x08\n\x04\x44\x41TA\x10\x04\"p\n\rAdvertMessage\x12\x1a\n\x12\x66inalDestinationIP\x18\x03 \x02(\t\x12\x0c\n\x04\x63\x65il\x18\x04 \x02(\x05\x12\x10\n\x08\x64\x65\x61\x64line\x18\x05 \x02(\x05\x12\x0c\n\x04\x66ine\x18\x06 \x02(\x05\x12\x15\n\rinitialBudget\x18\x07 \x02(\x05\"\x19\n\nBidMessage\x12\x0b\n\x03\x62id\x18\x04 \x02(\x05\"C\n\rBidWinMessage\x12\x10\n\x08winnerIP\x18\x04 \x02(\t\x12\x12\n\nwinningBid\x18\x05 \x02(\x05\x12\x0c\n\x04\x66ine\x18\x06 \x02(\x05\"\xc0\x01\n\x0c\x43heckMessage\x12\x12\n\nnewBalance\x18\x05 \x02(\x11\x12]\n\x0e\x62\x61lanceUpdates\x18\x06 \x03(\x0b\x32\x45.de.fu_berlin.maniac.packet_builder.CheckMessage.BalanceUpdateMessage\x1a=\n\x14\x42\x61lanceUpdateMessage\x12\x15\n\rtransactionID\x18\x01 \x02(\x05\x12\x0e\n\x06\x61mount\x18\x02 \x02(\x11\"q\n\x0b\x44\x61taMessage\x12\x1a\n\x12\x66inalDestinationIP\x18\x04 \x02(\t\x12\x10\n\x08\x64\x65\x61\x64line\x18\x05 \x02(\x05\x12\x0c\n\x04\x66ine\x18\x07 \x02(\x05\x12\x15\n\rinitialBudget\x18\x08 \x02(\x05\x12\x0f\n\x07payload\x18\t \x02(\t')



_PACKETMESSAGE_PACKETTYPE = _descriptor.EnumDescriptor(
  name='packetType',
  full_name='de.fu_berlin.maniac.packet_builder.PacketMessage.packetType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ADVERT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BID', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BIDWIN', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CHECK', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DATA', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=533,
  serialized_end=599,
)


_PACKETMESSAGE = _descriptor.Descriptor(
  name='PacketMessage',
  full_name='de.fu_berlin.maniac.packet_builder.PacketMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='de.fu_berlin.maniac.packet_builder.PacketMessage.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='transactionID', full_name='de.fu_berlin.maniac.packet_builder.PacketMessage.transactionID', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='advertMessage', full_name='de.fu_berlin.maniac.packet_builder.PacketMessage.advertMessage', index=2,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bidMessage', full_name='de.fu_berlin.maniac.packet_builder.PacketMessage.bidMessage', index=3,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bidWinMessage', full_name='de.fu_berlin.maniac.packet_builder.PacketMessage.bidWinMessage', index=4,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='checkMessage', full_name='de.fu_berlin.maniac.packet_builder.PacketMessage.checkMessage', index=5,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dataMessage', full_name='de.fu_berlin.maniac.packet_builder.PacketMessage.dataMessage', index=6,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PACKETMESSAGE_PACKETTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=59,
  serialized_end=599,
)


_ADVERTMESSAGE = _descriptor.Descriptor(
  name='AdvertMessage',
  full_name='de.fu_berlin.maniac.packet_builder.AdvertMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='finalDestinationIP', full_name='de.fu_berlin.maniac.packet_builder.AdvertMessage.finalDestinationIP', index=0,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ceil', full_name='de.fu_berlin.maniac.packet_builder.AdvertMessage.ceil', index=1,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='deadline', full_name='de.fu_berlin.maniac.packet_builder.AdvertMessage.deadline', index=2,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fine', full_name='de.fu_berlin.maniac.packet_builder.AdvertMessage.fine', index=3,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='initialBudget', full_name='de.fu_berlin.maniac.packet_builder.AdvertMessage.initialBudget', index=4,
      number=7, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=601,
  serialized_end=713,
)


_BIDMESSAGE = _descriptor.Descriptor(
  name='BidMessage',
  full_name='de.fu_berlin.maniac.packet_builder.BidMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bid', full_name='de.fu_berlin.maniac.packet_builder.BidMessage.bid', index=0,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=715,
  serialized_end=740,
)


_BIDWINMESSAGE = _descriptor.Descriptor(
  name='BidWinMessage',
  full_name='de.fu_berlin.maniac.packet_builder.BidWinMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='winnerIP', full_name='de.fu_berlin.maniac.packet_builder.BidWinMessage.winnerIP', index=0,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='winningBid', full_name='de.fu_berlin.maniac.packet_builder.BidWinMessage.winningBid', index=1,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fine', full_name='de.fu_berlin.maniac.packet_builder.BidWinMessage.fine', index=2,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=742,
  serialized_end=809,
)


_CHECKMESSAGE_BALANCEUPDATEMESSAGE = _descriptor.Descriptor(
  name='BalanceUpdateMessage',
  full_name='de.fu_berlin.maniac.packet_builder.CheckMessage.BalanceUpdateMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='transactionID', full_name='de.fu_berlin.maniac.packet_builder.CheckMessage.BalanceUpdateMessage.transactionID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='amount', full_name='de.fu_berlin.maniac.packet_builder.CheckMessage.BalanceUpdateMessage.amount', index=1,
      number=2, type=17, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=943,
  serialized_end=1004,
)

_CHECKMESSAGE = _descriptor.Descriptor(
  name='CheckMessage',
  full_name='de.fu_berlin.maniac.packet_builder.CheckMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='newBalance', full_name='de.fu_berlin.maniac.packet_builder.CheckMessage.newBalance', index=0,
      number=5, type=17, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='balanceUpdates', full_name='de.fu_berlin.maniac.packet_builder.CheckMessage.balanceUpdates', index=1,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_CHECKMESSAGE_BALANCEUPDATEMESSAGE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=812,
  serialized_end=1004,
)


_DATAMESSAGE = _descriptor.Descriptor(
  name='DataMessage',
  full_name='de.fu_berlin.maniac.packet_builder.DataMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='finalDestinationIP', full_name='de.fu_berlin.maniac.packet_builder.DataMessage.finalDestinationIP', index=0,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='deadline', full_name='de.fu_berlin.maniac.packet_builder.DataMessage.deadline', index=1,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fine', full_name='de.fu_berlin.maniac.packet_builder.DataMessage.fine', index=2,
      number=7, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='initialBudget', full_name='de.fu_berlin.maniac.packet_builder.DataMessage.initialBudget', index=3,
      number=8, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='payload', full_name='de.fu_berlin.maniac.packet_builder.DataMessage.payload', index=4,
      number=9, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=1006,
  serialized_end=1119,
)

_PACKETMESSAGE.fields_by_name['type'].enum_type = _PACKETMESSAGE_PACKETTYPE
_PACKETMESSAGE.fields_by_name['advertMessage'].message_type = _ADVERTMESSAGE
_PACKETMESSAGE.fields_by_name['bidMessage'].message_type = _BIDMESSAGE
_PACKETMESSAGE.fields_by_name['bidWinMessage'].message_type = _BIDWINMESSAGE
_PACKETMESSAGE.fields_by_name['checkMessage'].message_type = _CHECKMESSAGE
_PACKETMESSAGE.fields_by_name['dataMessage'].message_type = _DATAMESSAGE
_PACKETMESSAGE_PACKETTYPE.containing_type = _PACKETMESSAGE;
_CHECKMESSAGE_BALANCEUPDATEMESSAGE.containing_type = _CHECKMESSAGE;
_CHECKMESSAGE.fields_by_name['balanceUpdates'].message_type = _CHECKMESSAGE_BALANCEUPDATEMESSAGE
DESCRIPTOR.message_types_by_name['PacketMessage'] = _PACKETMESSAGE
DESCRIPTOR.message_types_by_name['AdvertMessage'] = _ADVERTMESSAGE
DESCRIPTOR.message_types_by_name['BidMessage'] = _BIDMESSAGE
DESCRIPTOR.message_types_by_name['BidWinMessage'] = _BIDWINMESSAGE
DESCRIPTOR.message_types_by_name['CheckMessage'] = _CHECKMESSAGE
DESCRIPTOR.message_types_by_name['DataMessage'] = _DATAMESSAGE

class PacketMessage(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PACKETMESSAGE

  # @@protoc_insertion_point(class_scope:de.fu_berlin.maniac.packet_builder.PacketMessage)

class AdvertMessage(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ADVERTMESSAGE

  # @@protoc_insertion_point(class_scope:de.fu_berlin.maniac.packet_builder.AdvertMessage)

class BidMessage(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BIDMESSAGE

  # @@protoc_insertion_point(class_scope:de.fu_berlin.maniac.packet_builder.BidMessage)

class BidWinMessage(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BIDWINMESSAGE

  # @@protoc_insertion_point(class_scope:de.fu_berlin.maniac.packet_builder.BidWinMessage)

class CheckMessage(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class BalanceUpdateMessage(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _CHECKMESSAGE_BALANCEUPDATEMESSAGE

    # @@protoc_insertion_point(class_scope:de.fu_berlin.maniac.packet_builder.CheckMessage.BalanceUpdateMessage)
  DESCRIPTOR = _CHECKMESSAGE

  # @@protoc_insertion_point(class_scope:de.fu_berlin.maniac.packet_builder.CheckMessage)

class DataMessage(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DATAMESSAGE

  # @@protoc_insertion_point(class_scope:de.fu_berlin.maniac.packet_builder.DataMessage)


# @@protoc_insertion_point(module_scope)
